### ISSUE TITLE
Update: Change loops and use Functions from Nftables package 

### ISSUE THREAD

**Issue by biplavxyz** [MasonCompetitiveCyber/vindicta#3]
1. Modify `GetAllTables()` and `GetAllChains()` functions -> Use `ListTables()` and `ListChains()` . 
2. Update  `GetFirewall()` function to list only the rules.
3. Enhance the UI.

**Comment by Txnn3r** [comment]
Updated in PR #8 . UI still needs enhanced & redundant functions need removed. Open to suggestions on UI solutions & new features.
